version: "2"
services:

    lb:
      image: dockercloud/haproxy:1.3
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
      ports:
        - 80:80
      links:
        - nginx1
        - nginx2


    nginx2:
      image: nginx
      volumes:
        - ./src:/usr/share/nginx/html
      environment:
        - VIRTUAL_HOST_WEIGHT=2
        - VIRTUAL_HOST=*/2
      logging:
        driver: syslog
        options:
          syslog-address: "udp://127.0.0.1:514"
          tag: nginx1


    nginx1:
      image: nginx
      volumes:
        - ./src:/usr/share/nginx/html
      environment:
        - VIRTUAL_HOST_WEIGHT=1
        - VIRTUAL_HOST=*
      logging:
        driver: syslog
        options:
          syslog-address: "udp://127.0.0.1:514"
          tag: nginx1


    syslog:
      build: ./build/syslog
      ports:
        - "127.0.0.1:514:514/udp"
      volumes:
        - ./logs:/var/log